In [3]:
#import necessary packages

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import ElasticNet
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [4]:
# import training data
df_train = pd.read_csv("train.csv")

In [5]:
df_train.head()

,Id,Product_Info_1,Product_Info_2,Product_Info_3,Product_Info_4,Product_Info_5,Product_Info_6,Product_Info_7,Ins_Age,Ht,...,Medical_Keyword_40,Medical_Keyword_41,Medical_Keyword_42,Medical_Keyword_43,Medical_Keyword_44,Medical_Keyword_45,Medical_Keyword_46,Medical_Keyword_47,Medical_Keyword_48,Response
0,2,1,D3,10,0.076923,2,1,1,0.641791,0.581818,...,0,0,0,0,0,0,0,0,0,8
1,5,1,A1,26,0.076923,2,3,1,0.059701,0.600000,...,0,0,0,0,0,0,0,0,0,4
2,6,1,E1,26,0.076923,2,3,1,0.029851,0.745455,...,0,0,0,0,0,0,0,0,0,8
3,7,1,D4,10,0.487179,2,3,1,0.164179,0.672727,...,0,0,0,0,0,0,0,0,0,8
4,8,1,D2,26,0.230769,2,3,1,0.417910,0.654545,...,0,0,0,0,0,0,0,0,0,8

In [14]:
df_train.describe()

,Id,Product_Info_1,Product_Info_3,Product_Info_4,Product_Info_5,Product_Info_6,Product_Info_7,Ins_Age,Ht,Wt,...,Medical_Keyword_40,Medical_Keyword_41,Medical_Keyword_42,Medical_Keyword_43,Medical_Keyword_44,Medical_Keyword_45,Medical_Keyword_46,Medical_Keyword_47,Medical_Keyword_48,Response
count,59381.000000,59381.000000,59381.000000,59381.000000,59381.000000,59381.000000,59381.000000,59381.000000,59381.000000,59381.000000,...,59381.000000,59381.000000,59381.000000,59381.000000,59381.000000,59381.000000,59381.000000,59381.000000,59381.000000,59381.000000
mean,39507.211515,1.026355,24.415655,0.328952,2.006955,2.673599,1.043583,0.405567,0.707283,0.292587,...,0.056954,0.010054,0.045536,0.010710,0.007528,0.013691,0.008488,0.019905,0.054496,5.636837
std,22815.883089,0.160191,5.072885,0.282562,0.083107,0.739103,0.291949,0.197190,0.074239,0.089037,...,0.231757,0.099764,0.208479,0.102937,0.086436,0.116207,0.091737,0.139676,0.226995,2.456833
min,2.000000,1.000000,1.000000,0.000000,2.000000,1.000000,1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,19780.000000,1.000000,26.000000,0.076923,2.000000,3.000000,1.000000,0.238806,0.654545,0.225941,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000
50%,39487.000000,1.000000,26.000000,0.230769,2.000000,3.000000,1.000000,0.402985,0.709091,0.288703,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000
75%,59211.000000,1.000000,26.000000,0.487179,2.000000,3.000000,1.000000,0.567164,0.763636,0.345188,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000
max,79146.000000,2.000000,38.000000,1.000000,3.000000,3.000000,3.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,8.000000

In [6]:
#separating data into different type of variables

cat_cols = ["Product_Info_1", "Product_Info_2", "Product_Info_3", "Product_Info_5", "Product_Info_6",\
                       "Product_Info_7", "Employment_Info_2", "Employment_Info_3", "Employment_Info_5", "InsuredInfo_1",\
                       "InsuredInfo_2", "InsuredInfo_3", "InsuredInfo_4", "InsuredInfo_5", "InsuredInfo_6", "InsuredInfo_7",\
                       "Insurance_History_1", "Insurance_History_2", "Insurance_History_3", "Insurance_History_4", "Insurance_History_7",\
                       "Insurance_History_8", "Insurance_History_9", "Family_Hist_1", "Medical_History_2", "Medical_History_3",\
                       "Medical_History_4", "Medical_History_5", "Medical_History_6", "Medical_History_7", "Medical_History_8",\
                       "Medical_History_9", "Medical_History_11", "Medical_History_12", "Medical_History_13", "Medical_History_14",\
                       "Medical_History_16", "Medical_History_17", "Medical_History_18", "Medical_History_19", "Medical_History_20",\
                       "Medical_History_21", "Medical_History_22", "Medical_History_23", "Medical_History_25", "Medical_History_26",\
                       "Medical_History_27", "Medical_History_28", "Medical_History_29", "Medical_History_30", "Medical_History_31",\
                       "Medical_History_33", "Medical_History_34", "Medical_History_35", "Medical_History_36", "Medical_History_37",\
                       "Medical_History_38", "Medical_History_39", "Medical_History_40", "Medical_History_41"]
con_cols = ["Product_Info_4", "Ins_Age", "Ht", "Wt", "BMI",
                      "Employment_Info_1", "Employment_Info_4", "Employment_Info_6",
                      "Insurance_History_5", "Family_Hist_2", "Family_Hist_3", "Family_Hist_4", "Family_Hist_5"]
dis_cols = ["Medical_History_1", "Medical_History_10", "Medical_History_15", "Medical_History_24", "Medical_History_32"]
dum_cols = ["Medical_Keyword_{}".format(i) for i in range(1, 48)]

In [7]:
#check columns for percentage of null values
columns = df_train.isnull().sum()/df_train.shape[0] * 100 
columns

Id                      0.000000
Product_Info_1          0.000000
Product_Info_2          0.000000
Product_Info_3          0.000000
Product_Info_4          0.000000
Product_Info_5          0.000000
Product_Info_6          0.000000
Product_Info_7          0.000000
Ins_Age                 0.000000
Ht                      0.000000
Wt                      0.000000
BMI                     0.000000
Employment_Info_1       0.031997
Employment_Info_2       0.000000
Employment_Info_3       0.000000
Employment_Info_4      11.416110
Employment_Info_5       0.000000
Employment_Info_6      18.278574
InsuredInfo_1           0.000000
InsuredInfo_2           0.000000
InsuredInfo_3           0.000000
InsuredInfo_4           0.000000
InsuredInfo_5           0.000000
InsuredInfo_6           0.000000
InsuredInfo_7           0.000000
Insurance_History_1     0.000000
Insurance_History_2     0.000000
Insurance_History_3     0.000000
Insurance_History_4     0.000000
Insurance_History_5    42.767889
                         ...
Medical_Keyword_20      0.000000
Medical_Keyword_21      0.000000
Medical_Keyword_22      0.000000
Medical_Keyword_23      0.000000
Medical_Keyword_24      0.000000
Medical_Keyword_25      0.000000
Medical_Keyword_26      0.000000
Medical_Keyword_27      0.000000
Medical_Keyword_28      0.000000
Medical_Keyword_29      0.000000
Medical_Keyword_30      0.000000
Medical_Keyword_31      0.000000
Medical_Keyword_32      0.000000
Medical_Keyword_33      0.000000
Medical_Keyword_34      0.000000
Medical_Keyword_35      0.000000
Medical_Keyword_36      0.000000
Medical_Keyword_37      0.000000
Medical_Keyword_38      0.000000
Medical_Keyword_39      0.000000
Medical_Keyword_40      0.000000
Medical_Keyword_41      0.000000
Medical_Keyword_42      0.000000
Medical_Keyword_43      0.000000
Medical_Keyword_44      0.000000
Medical_Keyword_45      0.000000
Medical_Keyword_46      0.000000
Medical_Keyword_47      0.000000
Medical_Keyword_48      0.000000
Response                0.000000
Length: 128, dtype: float64

In [8]:
#convert categorical data into dummies
df_train[cat_cols].applymap(str)
df_train_new = pd.get_dummies(df_train, columns=cat_cols, drop_first=True)

In [9]:
df_train_new.fillna(df_train_new.mean(), inplace=True).head()

,Id,Product_Info_4,Ins_Age,Ht,Wt,BMI,Employment_Info_1,Employment_Info_4,Employment_Info_6,Insurance_History_5,...,Medical_History_36_3,Medical_History_37_2,Medical_History_37_3,Medical_History_38_2,Medical_History_39_2,Medical_History_39_3,Medical_History_40_2,Medical_History_40_3,Medical_History_41_2,Medical_History_41_3
0,2,0.076923,0.641791,0.581818,0.148536,0.323008,0.028,0.0,0.361469,0.000667,...,0,1,0,0,0,1,0,1,0,1
1,5,0.076923,0.059701,0.600000,0.131799,0.272288,0.000,0.0,0.001800,0.000133,...,0,1,0,0,0,1,0,1,0,0
2,6,0.076923,0.029851,0.745455,0.288703,0.428780,0.030,0.0,0.030000,0.001733,...,1,1,0,0,0,1,0,1,0,0
3,7,0.487179,0.164179,0.672727,0.205021,0.352438,0.042,0.0,0.200000,0.001733,...,0,1,0,0,0,1,0,1,0,0
4,8,0.230769,0.417910,0.654545,0.234310,0.424046,0.027,0.0,0.050000,0.001733,...,1,1,0,0,0,1,0,1,0,0

In [10]:
scaler = StandardScaler()

In [11]:
X = df_train_new.drop('Response', axis=1)
Y = df_train_new.Response

In [22]:
steps = [('scaler', StandardScaler()), 
         ('regr_sc', RandomForestRegressor())]

In [23]:
pipeline = Pipeline(steps)

In [31]:
#Specify range for hyperparameters: parameters_reg
param_reg = {"regr_sc__max_depth": list(range(1,5))
              , "regr_sc__min_samples_split": [50,100,200]
              , "regr_sc__n_estimators": list(range(1,5))
              , "regr_sc__max_features": list(range(2,10))  }

In [32]:
#RandomForestRegressor after standard scaling: regr_cv
regr_cv =  GridSearchCV(pipeline, param_grid=param_reg, cv=5)

In [33]:
regr_sc = RandomForestRegressor()

In [34]:
regr_sc.fit(X, Y)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [38]:
regr_sc.score(X,Y)

0.88793851041654503